### PR TITLE
Stop assuming timeInForce is valid for order types

### PR DESCRIPTION
**Pull request by tomyan**
For one it doesn't work with STOP_LOSS

### CODE REVIEW

**Comment by balthazar** [comment]
Oh really I thought `GTC` was required for market orders?

**Comment by tomyan** [comment]
I don't know, but it wasn't valid for a STOP_LOSS order. Not sure if this is the right fix, but it solved the problem I was having. I'd be happy to pass the parameters required by the binance api, rather than having the client library do it transparently for me.

**Comment by balthazar** [comment]
Yep, you're right, thanks!

**Comment by balthazar** [comment]
Actually I've changed it so that it only adds it to `LIMIT`, `STOP_LOSS_LIMIT` or `TAKE_PROFIT_LIMIT` orders, the conditional was a bit faulty, but it provides a better experience for the users 🙂

**Comment by tomyan** [comment]
👍

**Pull request merged**
