### PR TITLE
Fix audit errors

### PR DESCRIPTION
**Pull request by JonathanLoscalzo**
- [x] fix audit errors
- [x] skip tests due to out of maintenance endpoint

### CODE REVIEW

**Comment by balthazar** [comment]
Thanks

**Comment by balthazar** [comment]
Actually can you PR this on the origin?

**Comment by JonathanLoscalzo** [comment]
> Actually can you PR this on the origin?

@balthazar what do You refer as "origin"? Without fork the repo?

**Comment by balthazar** [comment]
@JonathanLoscalzo you did a PR on the fork, the real repo is https://github.com/Ashlar/binance-api-node. Thanks!

**Comment by JonathanLoscalzo** [comment]
:man_facepalming:

**Pull request merged**
